variables:
  APP_NAME: "appNodeTesrt"

image: ubuntu:latest

stages:
  - test
  - build

test:
  stage: test
  image: node:18.19.1
  before_script:
    - echo "Running tests on $APP_NAME"
    - npm install
  script:
    - echo
    - npm run test
  cache:
    key: node_modules
    paths:
      - node_modules
  after_script:
    - echo "Tests complete"

build:
  stage: build
  image: docker:25.0
  services:
    - docker:25.0-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE .
  after_script:
    - docker push $DOCKER_IMAGE
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA